//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSchedule.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolSchedule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO lesson VALUES (&apos;2d1fb086-9035-474f-969b-e9075226e572&apos;, &apos;Русский язык&apos;);
        ///INSERT INTO lesson VALUES (&apos;36992aab-0fb2-47b4-b708-fd940e29385a&apos;, &apos;Математика&apos;);
        ///INSERT INTO lesson VALUES (&apos;6069ce14-a0bb-4013-88a9-003aedb0b14c&apos;, &apos;Литература&apos;);
        ///INSERT INTO lesson VALUES (&apos;46502add-4192-4818-a513-a7af766bccee&apos;, &apos;История&apos;);
        ///INSERT INTO lesson VALUES (&apos;64f88e58-415f-458c-9b68-67dbb46c4acc&apos;, &apos;География&apos;);
        ///
        ///
        ///INSERT INTO teacher VALUES (&apos;0320ca05-c65d-42f8-98da-05c64e49a038&apos;, &apos;Надежда&apos;, &apos;Ивановна&apos;, &apos;Пет [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE FUNCTION uuid() RETURNS varchar(256) AS &apos;
        ///	SELECT md5(random()::text || clock_timestamp()::text)::uuid
        ///&apos; LANGUAGE SQL;
        ///
        ///CREATE TABLE lesson (
        ///	id varchar NOT NULL PRIMARY KEY,
        ///	name varchar NOT NULL
        ///);
        ///
        ///CREATE TABLE teacher (
        ///	id varchar NOT NULL PRIMARY KEY,
        ///	first_name varchar NOT NULL,
        ///	mid_name varchar NOT NULL,
        ///	last_name varchar NOT NULL
        ///);
        ///
        ///CREATE TABLE teacher_lesson (
        ///	teacher_id varchar NOT NULL,
        ///	lesson_id varchar NOT NULL,
        ///	PRIMARY KEY (teacher_id, lesson_id),
        ///	CONSTRA [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string V1_00_01__Main {
            get {
                return ResourceManager.GetString("V1_00_01__Main", resourceCulture);
            }
        }
    }
}
